# Code generated by op-codegen - DO NO EDIT MANUALLY

from __future__ import annotations
import weakref
from .core import Core, UniffiCore
from .desktop_core import DesktopCore
from .defaults import new_default_config, DesktopAuth
from .secrets import Secrets
from .items import Items
from .vaults import Vaults


class Client:
    secrets: Secrets
    items: Items
    vaults: Vaults

    @classmethod
    async def authenticate(
        cls, auth: str | DesktopAuth, integration_name: str, integration_version: str
    ) -> Client:
        config = new_default_config(
            auth=auth,
            integration_name=integration_name,
            integration_version=integration_version,
        )

        if isinstance(auth, str):
            core = UniffiCore()
        elif isinstance(auth, DesktopAuth):
            core = DesktopCore()

        client_id = int(await core.init_client(config))

        authenticated_client = cls()

        authenticated_client.secrets = Secrets(client_id, core)
        authenticated_client.items = Items(client_id, core)
        authenticated_client.vaults = Vaults(client_id, core)
        authenticated_client._finalizer = weakref.finalize(
            cls, _release_client, client_id
        )

        return authenticated_client
