# Code generated by op-codegen - DO NO EDIT MANUALLY

from .core import InnerClient
from pydantic import TypeAdapter
from .types import GetVariablesResponse


class Environments:
    """
    The Environments API holds all the operations the SDK client can perform on 1Password Environments (Vault Type = 'D').
    """

    def __init__(self, inner_client: InnerClient):
        self.inner_client = inner_client

    async def get_variables(self, environment_id: str) -> GetVariablesResponse:
        """
        Get environment variables belonging to an Environment.
        """
        response = await self.inner_client.invoke(
            {
                "invocation": {
                    "clientId": self.inner_client.client_id,
                    "parameters": {
                        "name": "EnvironmentsGetVariables",
                        "parameters": {"environment_id": environment_id},
                    },
                }
            }
        )

        response = TypeAdapter(GetVariablesResponse).validate_json(response)
        return response
