# Code generated by op-codegen - DO NO EDIT MANUALLY

from .core import Core
from pydantic import TypeAdapter
from .types import Group, GroupGetParams


class Groups:
    """
    The Groups API holds all the operations the SDK client can perform on 1Password groups.
    """

    def __init__(self, client_id, core: Core):
        self.client_id = client_id

    async def get(self, group_id: str, group_params: GroupGetParams) -> Group:
        response = await self.core.invoke(
            {
                "invocation": {
                    "clientId": self.client_id,
                    "parameters": {
                        "name": "GroupsGet",
                        "parameters": {
                            "group_id": group_id,
                            "group_params": group_params.model_dump(by_alias=True),
                        },
                    },
                }
            }
        )

        response = TypeAdapter(Group).validate_json(response)
        return response
