# Code generated by op-codegen - DO NO EDIT MANUALLY

from .core import _invoke, _invoke_sync
from json import loads
from .iterator import SDKIterator
from .types import Item, ItemsShareAccountPolicy, ItemsShareParams, ValidRecipient


class ItemsShare:
    def __init__(self, client_id):
        self.client_id = client_id

    async def get_account_policy(
        self, vault_id: str, item_id: str
    ) -> ItemsShareAccountPolicy:
        response = await _invoke(
            {
                "invocation": {
                    "clientId": self.client_id,
                    "parameters": {
                        "name": "ItemsShareGetAccountPolicy",
                        "parameters": {"vault_id": vault_id, "item_id": item_id},
                    },
                }
            }
        )
        return ItemsShareAccountPolicy.model_validate_json(response)

    async def validate_recipients(
        self, policy: ItemsShareAccountPolicy, recipients: list[str]
    ) -> list[ValidRecipient]:
        response = await _invoke(
            {
                "invocation": {
                    "clientId": self.client_id,
                    "parameters": {
                        "name": "ItemsShareValidateRecipients",
                        "parameters": {
                            "policy": policy.model_dump(by_alias=True),
                            "recipients": recipients,
                        },
                    },
                }
            }
        )

        response = loads(response)
        response = [ValidRecipient.model_validate(data) for data in response]
        return response

    async def create(
        self, item: Item, policy: ItemsShareAccountPolicy, params: ItemsShareParams
    ) -> str:
        response = await _invoke(
            {
                "invocation": {
                    "clientId": self.client_id,
                    "parameters": {
                        "name": "ItemsShareCreate",
                        "parameters": {
                            "item": item.model_dump(by_alias=True),
                            "policy": policy.model_dump(by_alias=True),
                            "params": params.model_dump(by_alias=True),
                        },
                    },
                }
            }
        )
        return str(loads(response))
