"""
Generated by typeshare 1.10.0-beta.7
"""

from __future__ import annotations

from pydantic import BaseModel, Field, ConfigDict
from typing import Annotated, List, Literal, Optional


class Item(BaseModel):
    """
    Represents a 1Password item.
    """
    model_config = ConfigDict(populate_by_name=True)

    id: str
    """
    The item's ID
    """
    title: str
    """
    The item's title
    """
    category: ItemCategory
    """
    The item's category
    """
    vault_id: Annotated[str, Field(alias="vaultId")]
    """
    The ID of the vault where the item is saved
    """
    fields: List[ItemField]
    """
    The item's fields
    """
    sections: List[ItemSection]
    """
    The item's sections
    """
    version: int
    """
    The item's version
    """


ItemCategory = Literal[
    "Login",
    "SecureNote",
    "CreditCard",
    "CryptoWallet",
    "Identity",
    "Password",
    "Document",
    "ApiCredentials",
    "BankAccount",
    "Database",
    "DriverLicense",
    "Email",
    "MedicalRecord",
    "Membership",
    "OutdoorLicense",
    "Passport",
    "Rewards",
    "Router",
    "Server",
    "SshKey",
    "SocialSecurityNumber",
    "SoftwareLicense",
    "Person",
    "Unsupported",
]


class ItemCreateParams(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
     
    category: ItemCategory
    """
    The item's category
    """
    vault_id: Annotated[str, Field(alias="vaultId")]
    """
    The ID of the vault where the item is saved
    """
    title: str
    """
    The item's title
    """
    fields: List[ItemField]
    """
    The item's fields
    """
    sections: List[ItemSection]
    """
    The item's sections
    """


class ItemField(BaseModel):
    model_config = ConfigDict(populate_by_name=True) 
    """
    Represents a field within an item.
    """

    id: str
    """
    The field's ID
    """
    title: str
    """
    The field's title
    """
    section_id: Annotated[Optional[str], Field(alias="sectionId")]
    """
    The ID of the section containing the field. Built-in fields such as usernames and passwords don't require a section.
    """
    field_type: Annotated[ItemFieldType, Field(alias="fieldType")]
    """
    The field's type
    """
    value: str
    """
    The string representation of the field's value
    """
    details: [ItemFieldDetails]
    """
    Field type-specific attributes. Must be set to None.
    """


class ItemFieldDetailsOtp(BaseModel):
    type: Literal["Otp"]
    content: OtpFieldDetails


ItemFieldDetails = ItemFieldDetailsOtp
"""
Field type-specific attributes.
"""

ItemFieldType = Literal[
    "Text", "Concealed", "CreditCardType", "Phone", "Url", "Totp", "Unsupported"
]


class ItemOverview(BaseModel):
    model_config = ConfigDict(populate_by_name=True) 
    """
    Represents a decrypted 1Password item.
    """

    id: str
    """
    The item's ID
    """
    title: str
    """
    The item's title
    """
    category: ItemCategory
    """
    The item's category
    """
    vault_id: Annotated[str, Field(alias="vaultId")]
    """
    The ID of the vault where the item is saved
    """


class ItemSection(BaseModel):
    """
    A section groups together multiple fields in an item.
    """

    id: str
    """
    The section's unique ID
    """
    title: str
    """
    The section's title
    """


class OtpFieldDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True) 
    """
    Additional attributes for OTP fields.
    """

    code: Optional[str]
    """
    The OTP code, if successfully computed
    """
    error_message: Annotated[Optional[str], Field(alias="errorMessage")]
    """
    The error message, if the OTP code could not be computed
    """


class VaultOverview(BaseModel):
    """
    Represents a decrypted 1Password vault.
    """

    id: str
    """
    The vault's ID
    """
    title: str
    """
    The vault's title
    """
