name: Prep Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number:"
        required: true
        type: string
      build_number:
        description: "Build number:"
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/') # Only run on branches that start with sdk-core/
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Parse and Validate Inputs
        id: get_inputs
        run: |
          # Get inputs passed to the workflow
          VERSION="${{ github.event.inputs.version }}"
          BUILD_NUMBER="${{ github.event.inputs.build_number }}"

          # Save the parsed values for future steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
        shell: bash

      - name: Run the Prep Release Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make prep-release VERSION="$VERSION" BUILD_NUMBER="$BUILD_NUMBER"
        shell: bash
