name: Release Python SDKs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version for the SDKs in the format of M.m.p"
        required: true
        type: string
      build_number:
        description: "New build number for the SDKs in the format of Mmmppbb "
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/') # Only run on branches that start with sdk-core/
    env:
      VERSION: ${{ github.event.inputs.version }}
      BUILD_NUMBER: ${{ github.event.inputs.build_number }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Run the Prep Release Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make prep-release VERSION="{{ env.SDK_VERSION }}" BUILD_NUMBER="{{ env.SDK_BUILD_NUMBER }}"
        shell: bash

  build-wheels:
    name: Build wheels for Python SDK on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/heads/sdk-core/')
    needs: [prepare-release]
    strategy:
      # we don't want all of them failing if one fails
      fail-fast: false
      matrix:
        # macOS 13 is an Intel runner and macOS 14 is an Apple Silicon runner
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Upgrade build dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      # Need to grab the SDK version for the wheel name
      - name: Extract SDK Version
        run: echo "SDK_VERSION=$(cat .VERSION)" >> "$GITHUB_ENV"
        shell: bash

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          # Skip all the unneeded images like PyPy and musllinux images
          CIBW_SKIP: pp* *-musllinux_*
          # Set the manylinux X86_64/aarch64 image to this specific 2.34 image
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_34_x86_64"
          CIBW_MANYLINUX_AARCH64_IMAGE: "quay.io/pypa/manylinux_2_34_aarch64"
          # Set the wheel to the native archtiecture (output of platform.machine() which we use in the setup.py script)
          CIBW_ARCHS: "native"
          # Windows reparing of wheels are not supported so manually install it.
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
          # Dependencies required for testing each wheel
          CIBW_TEST_REQUIRES: "pydantic pytest pytest-asyncio"
          # The minimum MacOS version for darwin wheels (matches OPH)
          MACOSX_DEPLOYMENT_TARGET: "12.0"
          # The command to test every wheel
          CIBW_TEST_COMMAND: "python -m pytest {project}/src/onepassword/test_client.py"
          # Pass the service account token in all wheel buildings for testing of the wheels.
          CIBW_ENVIRONMENT: OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.TEST_SERVICE_ACCOUNT_TOKEN }}
        run: |
          python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: onepassword-sdk-${{ env.SDK_VERSION }}-${{ matrix.os }}
          path: ./dist/*.whl

  build-sdist:
    name: Build source distribution for Python SDK
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/')
    needs: [prepare-release]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        # Need to grab the SDK version for the wheel name
      - name: Extract SDK Version
        run: echo "SDK_VERSION=$(cat .VERSION)" >> "$GITHUB_ENV"
        shell: bash

      - name: Install dependencies
        run: pip3 install build pydantic pytest pytest-asyncio

      - name: Build source distribution
        run: python3 -m build --sdist

      - name: Test Source Distribution
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.TEST_SERVICE_ACCOUNT_TOKEN }}
        run: |
          python3 -m pip install dist/*.tar.gz
          python3 -m pytest src/onepassword/test_client.py

      - uses: actions/upload-artifact@v4
        with:
          name: onepassword-sdk-${{ env.SDK_VERSION }}
          path: ./dist/*.tar.gz

  Release-SDK:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/') # Only run on branches that start with sdk-core/
    needs: [build-wheels, build-sdist]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Run the Release Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release
        shell: bash

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/sdk-core/')
    environment:
      name: pypi
      url: https://pypi.org/project/onepassword-sdk/
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    needs: [Release-SDK]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: onepassword-sdk-*
          path: ./dist
          merge-multiple: true
      - name: Publish package distributions to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.12
